### ISSUE TITLE
Alert boxes aren't responsive to mobile displays

### ISSUE THREAD

**Issue by unpredictable** [88/username-lookup#5]
Steps to reproduce: Resize window to fit mobile screen size or use a mobile device. There will be no padding for the alert box, nor will the contents of the alert box fit to the screen size. Most likely due to a fixed width in CSS but I'm unaware of a better way to go about *not* having it take up the entire screen on desktop...

Image:
![img](https://i.gyazo.com/4efc2eeb3287e4c9dca142e041ae2518.gif)

**Comment by tanpug** [comment]
fixed waiting 4 push
