### ISSUE TITLE
PHD checker isn't centered

### ISSUE THREAD

**Issue by unpredictable** [88/username-lookup#7]
Bad with CSS, which this issue probably is focused on, so I'm reporting it.

Image:
![img](https://i.gyazo.com/fc5d732531af262292788597cc32d807.png)

**Comment by tanpug** [comment]
fixed will push

**Comment by unpredictable** [comment]
Was able to reproduce this still. Pain

**Comment by tanpug** [comment]
working for others might be a you issue LLL

**Comment by unpredictable** [comment]
LOOOOOOL

**Comment by unpredictable** [comment]
Fixed in [`1fe56ed`](https://github.com/88/username-lookup/commit/1fe56ed3d8a06bb8107b49a76d07356e7f82278e)
